version: "3.8"

services:
  api:
    build:
      context: ./backend
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_URL=http://localhost
      - DB_CONNECTION=sqlite

  nginx:
    image: nginx:alpine
    volumes:
      - ./backend/docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./backend:/var/www/html:ro
    ports:
      - "80:80"

volumes:
  laravel-data:

